### ISSUE TITLE
realpath returns wrong results for files > 2GB

### ISSUE THREAD

**Issue by vhalasu** [jkuchar/BigFileTools#1]
Env.: PHP 5.3.5, 64bit machine with 32bit Suse linux 11.4
Tried with 670MB, 2.6GB, 4.6GB and 6.8GB files and symlinks to them.

For regular files the behavior is consistently wrong: if file size is over PHP_INT_MAX, realpath return FALSE. Results for symlinks are rather unsure: if you call `clearstatcache` before `realpath`, you'll get the same as with regular files. Without `clearstatcache` however, realpath for first time return FALSE, then after refreshing the page it starts returning resolved symlink (= absolute path to file). If you don't refresh the page for approx 30sec, you're back on the beginning - first FALSE, then correct path.

This affects mainly the `sizeCurl` method - if `realpath` (that is, `this->$path` after calling `absolutizePath`) returns FALSE, then the address resolves to `file://` and the size of current directory is returned.

The same applied for regular files on FAT32 partition (no symlinks of course and only the two smallest).

Found some realpath replacement here: http://stackoverflow.com/questions/4049856/replace-phps-realpath , but didn't try it yet. Personally I'm using absolute paths whenever possible.

**Comment by jkuchar** [comment]
Closed due to innactivity. Reopen anytime if it is still relevant.
