### ISSUE TITLE
Error thrown on existing file of 0kb

### ISSUE THREAD

**Issue by benjamineukles** [jkuchar/BigFileTools#19]
Hi,

I get an error when I'm using the getSize method on an existing but empty file (0Kb).
The message displayed by the thrown error is: Can not size of file XXXX

This error is thrown at the end of the getSize method in BigFileTools.php.

I've checked the $return variable that is set by each way of getting size and I get this :

1. with curl $return equals 0
2. with native seek too
3. with Com too
4. with exec it equals false

So it looks like if we modify each if statement over $return from:
`if ($return) {
			return $return;
		}`

to: 

`if ($return !== false) {
			return $return;
		}`

this should work properly.

Please can you do this modification or fix the problem in an other way for empty file?

Regards.

**Comment by jkuchar** [comment]
You should see in a minute build results with the empty file.

**Comment by jkuchar** [comment]
@benjamineukles Take look into into build results. There are HUGE platform behaviour deviations. I'm curious how to get this fixed. I'm currently on Windows so I can fix exec driver which fails on Windows. Could you please try to fix this on Linux and Mac? (looks like the behaviour is the same on these two)

**Comment by benjamineukles** [comment]
Unfortunately I can't because I'm on Windows too.

**Comment by jkuchar** [comment]
Fortunately build passed on Windows, Linux and Mac. So, done.

**Comment by benjamineukles** [comment]
Perfect, thank you!
