### ISSUE TITLE
is_file (and fopen) fails with files > 2GB

### ISSUE THREAD

**Issue by vhalasu** [jkuchar/BigFileTools#3]
This affects path validation in constructor. For files with size over PHP_INT_MAX `is_file` returns FALSE. Functions `is_link`, `is_dir`, `is_readable`, `file_exists` are not affected. I tried following:
```
if (file_exists($path) && (is_file($path) || !is_file($path) && !is_dir($path)))
    $this->path = $path;
```
For files under 2GB works `file_exists && is_file` as before, and for bigger ones `file_exists && !is_file && !is_dir`. I'm not sure if this is optimal, I just hope there are no file types that would return FALSE for both `is_file` and `is_dir`. :-)

Env.: PHP 5.3.5, 64bit machine with 32bit Suse linux 11.4
Tried with 670MB, 2.6GB, 4.6GB and 6.8GB files and symlinks to them.

**Comment by jkuchar** [comment]
Closed due to innactivity. Reopen anytime if it is still relevant.
